### ISSUE TITLE
Hard dependency on GLX on Linux

### ISSUE THREAD

**Issue by PoroCYon** [floriankirsch/OpenCSG#1]
This breaks for me, as I'm using Wayland (and thus EGL).

**Comment by sl1pkn07** [comment]
same problem here. fails to build with glew with wayland support

**Comment by t-paul** [comment]
Decoupling from GLX would be useful for OpenSCAD too, currently I'm building a patched version of OpenCSG for creating a Docker container running OpenSCAD with EGL headless support (e.g. no need for running Xvfb):

https://github.com/openscad/docker-openscad/blob/641845c46a7038a370afa7781b2177eeae68bca6/openscad/bookworm/Dockerfile.egl#L68-L80

**Comment by t-paul** [comment]
@cjmayo nice, I have not looked into the Wayland topic other than Qt defaulting to Wayland recently. Good to know it would help for this case too. And thanks for the PR, I never found the time to polish the hackery linked above.

**Comment by sl1pkn07** [comment]
Hi. is possible add a qmake flag for disable `OPENCSG_HAVE_PBUFFER` without edit  by hand `src/opencsgConfig.h` file?

also, as note, the example opencsgexample working in X11 mode, not wayland :(

greetings

**Comment by kintel** [comment]
Considering Glew is either GLX or EGL, perhaps a cleaner approach would be to decouple from Glew, to allow programs using OpenCSG to choose to use GLX, EGL, or both?

If we disregard PBuffer support, OpenCSG should only really need pure OpenGL bindings, so it shouldn't need to meddle with context creation stuff, like Glew does.

**Comment by kintel** [comment]
I opened https://github.com/floriankirsch/OpenCSG/pull/9 to remove the need for non-core OpenGL bindings. My next step is likely to add support for changing GL wrangler library; specifically I want to support GLAD. That should remove the GLX dependency.

**Comment by floriankirsch** [comment]
Replacing GLEW by glad should indeed remove the GLX dependency. I have implemented this today. Hopefully it already works on all platforms.

**Comment by kintel** [comment]
Cool! How did you solve GLAD initialization?

**Comment by floriankirsch** [comment]
Hm, I just call gladLoadGL() without parameters. Only glad version 1 appears to provide this; with version 2 this function requires to provide a function pointer for some GetProcAddress like function. So I used glad 1 for now.
Right now I call gladLoadGL() per context. This may be incorrect, probably it must be called per context switch - I still have to figure that out.

**Comment by kintel** [comment]
In GLAD2 it's called `gladLoaderLoadGL()`.

I'm not sure though, how to best manage GLAD when build application with OpenGL code in shared libraries, especially if the application also uses GLAD, but potentially a different version with different settings.

**Comment by floriankirsch** [comment]
Thank you Marius, maybe I will retry glad 2 again. 

I also see that https://github.com/Dav1dde/glad/wiki/C has section on multiple context.

**Comment by kintel** [comment]
Humm, how did you do multi-context in the past?
I believe per-context function pointers is a Windows-specific limitation, and only important if an app uses multiple different device contexts.

**Comment by floriankirsch** [comment]
Interestingly multi-context support was added for an 2010-version of OpenSCAD, that had optional support for an MDI interface. This was supported only on Linux. So maybe I did not care about extension loading in several contexts - or I did not even notice.
I guess I can ignore this for now.

**Comment by kintel** [comment]
Yeah, but on Linux, AFAIU, OpenGL entry points can be used across contexts, and I think it's really hard to end up in a situation where that's not supported. My understanding (although it's been a while) is that the multi context stuff is really only used to manage per-context _resources_, not per-context entry points.

**Comment by floriankirsch** [comment]
OpenCSG 1.6.0 comes with this change. OpenCSG does not depend on GLX anymore. Closing the issue.
