### ISSUE TITLE
Make GLEW optional

### ISSUE THREAD

**Issue by kintel** [floriankirsch/OpenCSG#10]
GLEW is problematic on Linux, as it's built either against EGL or GLX, and Linux distros tend to ship _only_ the GLX build. This makes it hard to ship EGL-based software using OpenCSG.

Feature request: Make GLEW optional, and allow using another GL wrangler instead, which isn't tied to GLX or EGL exclusively. GLAD is an option: https://github.com/Dav1dde/glad

This is related to #1 but calls out a feature request rather than a symptom.

**Comment by floriankirsch** [comment]
Today, I have build in glad and at the same time removed GLEW. This worked well, but some general testing would be appreciated to see whether the changes are compatible, in particular on the Mac.

**Comment by floriankirsch** [comment]
OpenCSG 1.6.0 uses Glad now instead of GLEW. The Glad symbols are put into a private namespace, so this should not conflict sich any other applications that already use Glad. Closing the issue.

**Comment by t-paul** [comment]
Awesome :heart_eyes:, thank you. I'll try to find some time to update the headless Docker image of OpenSCAD removing all the hacks that were needed for EGL.
